print('กรอกข้อมูลส่วนตัว')
name = input("กรอกชื่อ :\n")
nickname = input("กรอกชื่อเล่น :\n")
age = input("กรอกอายุ :\n")
id = input("กรอกรหัสประจำตัวนักเรียน :\n")
no = input("กรอกชั้นปี :\n")
height = float(input("กรอกส่วนสูง :\n"))
weight = float(input("กรอกน้ำหนัก :\n"))
hw = height+weight
print('ประวัติโดยย่อ')
print(f"ชื่อ : {name} อายุ : {age} ")
print(f"รหัสประจำตัวนักเรียน :{id} ระดับชั้น : {no} ")
print(f"ชื่อเล่น : {nickname}")
print(f"ส่วนสูง : {height} เซนติเมตร น้ำหนัก : {weight} กิโลกรัม")
print(f"ส่วนสูง + น้ำหนัก : {hw}")